// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {win32} from '../models';

export function EnumAppProcessInfo():Promise<Array<win32.ProcessInfo>>;

export function ReadBytes(arg1:number,arg2:string,arg3:number):Promise<Array<number>>;

export function StartRecording(arg1:number,arg2:string,arg3:number,arg4:number):Promise<void>;

export function StopRecord():Promise<void>;
