// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnumAppProcessInfo() {
  return window['go']['main']['App']['EnumAppProcessInfo']();
}

export function ReadBytes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadBytes'](arg1, arg2, arg3);
}

export function StartRecording(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2, arg3, arg4);
}

export function StopRecord() {
  return window['go']['main']['App']['StopRecord']();
}
